INSERT INTO LANGUAGE(SHORT_NAME,FULL_NAME,ENABLED) VALUES('EN','English',TRUE);
INSERT INTO LANGUAGE(SHORT_NAME,FULL_NAME,ENABLED,MAJOR) VALUES('RU','Русский',TRUE,TRUE);
INSERT INTO LANGUAGE(SHORT_NAME,FULL_NAME,ENABLED) VALUES('UA','Українська',TRUE);